### ISSUE TITLE
Results overview: total number off quizzes wrong

### ISSUE THREAD

**Issue by Semphora** [anabrid/analog-advent#17]
On he results overview the number of participated tasks is stated as x "of 21 quizzes"

24 days
- day 1 registration
- day 12 no quizz
- day 20 no contend
- day 24 results

Should be 20 quizzes, not 21.

**Comment by svenk** [comment]
Yes that's right. Fixed by 29cc211a5ea04c547215d8a02bc23b78bfb20b3f and now correctly handled.

**Comment by Semphora** [comment]
the total number of quizzes is still listed as x out of 21 on the results page.
